### ISSUE TITLE
Not working service

### ISSUE THREAD

**Issue by lifaon74** [Kollate/Truegit#1]
H, I tested your service without success:

- I forked the demo repo: https://github.com/lifaon74/truegit-test
- Then installed the app:
![image](https://user-images.githubusercontent.com/6762756/171426400-75d26cbe-4d07-4a60-8871-e077b0547fca.png)
- and finally connected with my github account:
![image](https://user-images.githubusercontent.com/6762756/171426731-51a5b54b-5932-4431-8a0a-e5b688b22142.png)

However, the blob is not displayed on the dashboard, nor available using this link: https://lifaon74-truegit-test.truegit.io/

Maybe too early adopter ?

**Comment by quant-daddy** [comment]
Hi @lifaon74, sorry about this. We are fixing some of our backend code so ideally it should be ready to use in a couple of days. I did fix this bug. For now, if you reinstall the github app in your account, it should work.
